### ISSUE TITLE
load input netcdf data from OpenDAP

### ISSUE THREAD

**Issue by epifanio** [johtj/yopp_vis_tools#1]
Hi, I see you have hardcoded few input netcdf  files in the code. It will be great if you can point us to the file you intend to use as test - so we can upload them on our OpenbDAP server. This way we can load the file from the the OpenDAP server and  will be easier to run and reproduce the notebooks.

**Comment by johtj** [comment]
All files used that are in the portal should now have been replaced with fetching through OpenDAP. The exception to this is the observation files as there are none in the portal, if we could add one for testing purposes that would be great!
